"""empty message

Revision ID: 33dd1f0fe9f6
Revises: 
Create Date: 2025-05-14 12:27:46.930271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dd1f0fe9f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_delivery_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', name='deliverystatus'), nullable=False),
    sa.Column('dimensions', sa.String(), nullable=False),
    sa.Column('address_in', sa.String(), nullable=False),
    sa.Column('address_out', sa.String(), nullable=False),
    sa.Column('datetime_in', sa.DateTime(), nullable=False),
    sa.Column('datetime_out', sa.DateTime(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.ForeignKeyConstraint(['user_delivery_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.drop_table('users')
    op.drop_table('transports')
    op.drop_table('roles')
    # ### end Alembic commands ###
